package actions

import (
	"github.com/angelo-marano/airport/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Waittime)
// DB Table: Plural (waittimes)
// Resource: Plural (Waittimes)
// Path: Plural (/waittimes)
// View Template Folder: Plural (/templates/waittimes/)

// WaittimesResource is the resource for the Waittime model
type WaittimesResource struct {
	buffalo.Resource
}

// List gets all Waittimes. This function is mapped to the path
// GET /waittimes
func (v WaittimesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	waittimes := &models.Waittimes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Waittimes from the DB
	if err := q.All(waittimes); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, waittimes))
}

// Show gets the data for one Waittime. This function is mapped to
// the path GET /waittimes/{waittime_id}
func (v WaittimesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Waittime
	waittime := &models.Waittime{}

	// To find the Waittime the parameter waittime_id is used.
	if err := tx.Find(waittime, c.Param("waittime_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, waittime))
}

// New renders the form for creating a new Waittime.
// This function is mapped to the path GET /waittimes/new
func (v WaittimesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Waittime{}))
}

// Create adds a Waittime to the DB. This function is mapped to the
// path POST /waittimes
func (v WaittimesResource) Create(c buffalo.Context) error {
	// Allocate an empty Waittime
	waittime := &models.Waittime{}

	// Bind waittime to the html form elements
	if err := c.Bind(waittime); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(waittime)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, waittime))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Waittime was created successfully")

	// and redirect to the waittimes index page
	return c.Render(201, r.Auto(c, waittime))
}

// Edit renders a edit form for a Waittime. This function is
// mapped to the path GET /waittimes/{waittime_id}/edit
func (v WaittimesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Waittime
	waittime := &models.Waittime{}

	if err := tx.Find(waittime, c.Param("waittime_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, waittime))
}

// Update changes a Waittime in the DB. This function is mapped to
// the path PUT /waittimes/{waittime_id}
func (v WaittimesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Waittime
	waittime := &models.Waittime{}

	if err := tx.Find(waittime, c.Param("waittime_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Waittime to the html form elements
	if err := c.Bind(waittime); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(waittime)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, waittime))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Waittime was updated successfully")

	// and redirect to the waittimes index page
	return c.Render(200, r.Auto(c, waittime))
}

// Destroy deletes a Waittime from the DB. This function is mapped
// to the path DELETE /waittimes/{waittime_id}
func (v WaittimesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Waittime
	waittime := &models.Waittime{}

	// To find the Waittime the parameter waittime_id is used.
	if err := tx.Find(waittime, c.Param("waittime_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(waittime); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Waittime was destroyed successfully")

	// Redirect to the waittimes index page
	return c.Render(200, r.Auto(c, waittime))
}
